spring:
  application:
    name: '@project.artifactId@'

server:
  port: ${PORT}

eureka:
  instance:
    hostname: https://eureka-server-spring.herokuapp.com/
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: https://eureka-server-spring.herokuapp.com/eureka/